let cgroup_headers = [
    { id: 'time', title: 'TIME' },
    { id: 'anon', title: 'ANON' },
    { id: 'file', title: 'FILE' },
    { id: 'kernel', title: 'KERNEL' },
    { id: 'kernel_stack', title: 'KERNEL STACK' },
    { id: 'pagetables', title: 'PAGETABLES' },
    { id: 'sec_pagetables', title: 'SEC PAGETABLES' },
    { id: 'percpu', title: 'PERCPU' },
    { id: 'sock', title: 'SOCK' },
    { id: 'vmalloc', title: 'VMALLOC' },
    { id: 'shmem', title: 'SHMEM' },
    { id: 'zswap', title: 'ZSWAP' },
    { id: 'zswapped', title: 'ZSWAPPED' },
    { id: 'file_mapped', title: 'FILE MAPPED' },
    { id: 'file_dirty', title: 'FILE DIRTY' },
    { id: 'file_writeback', title: 'FILE WRITEBACK' },
    { id: 'swapcached', title: 'SWAPCACHED' },
    { id: 'anon_thp', title: 'ANON THP' },
    { id: 'file_thp', title: 'FILE THP' },
    { id: 'shmem_thp', title: 'SHMEM THP' },
    { id: 'inactive_anon', title: 'INACTIVE ANON' },
    { id: 'active_anon', title: 'ACTIVE ANON' },
    { id: 'inactive_file', title: 'INACTIVE FILE' },
    { id: 'active_file', title: 'ACTIVE FILE' },
    { id: 'unevictable', title: 'UNEVICTABLE' },
    { id: 'slab_reclaimable', title: 'SLAB RECLAIMABLE' },
    { id: 'slab_unreclaimable', title: 'SLAB UNRECLAIMABLE' },
    { id: 'slab', title: 'SLAB' },
    { id: 'workingset_refault_anon', title: 'WORKINGSET REFAULT ANON' },
    { id: 'workingset_refault_file', title: 'WORKINGSET REFAULT FILE' },
    { id: 'workingset_activate_anon', title: 'WORKINGSET ACTIVATE ANON' },
    { id: 'workingset_activate_file', title: 'WORKINGSET ACTIVATE FILE' },
    { id: 'workingset_restore_anon', title: 'WORKINGSET RESTORE ANON' },
    { id: 'workingset_restore_file', title: 'WORKINGSET RESTORE FILE' },
    { id: 'workingset_nodereclaim', title: 'WORKINGSET NODERECLAIM' },
    { id: 'pgdemote_kswapd', title: 'PGDEMOTE KSWAPD' },
    { id: 'pgdemote_direct', title: 'PGDEMOTE DIRECT' },
    { id: 'pgdemote_khugepaged', title: 'PGDEMOTE KHUGEPAGED' },
    { id: 'pgpromote_success', title: 'PGPROMOTE SUCCESS' },
    { id: 'pgscan', title: 'PGSCAN' },
    { id: 'pgsteal', title: 'PGSTEAL' },
    { id: 'pgscan_kswapd', title: 'PGSCAN KSWAPD' },
    { id: 'pgscan_direct', title: 'PGSCAN DIRECT' },
    { id: 'pgscan_khugepaged', title: 'PGSCAN KHUGEPAGED' },
    { id: 'pgsteal_kswapd', title: 'PGSTEAL KSWAPD' },
    { id: 'pgsteal_direct', title: 'PGSTEAL DIRECT' },
    { id: 'pgsteal_khugepaged', title: 'PGSTEAL KHUGEPAGED' },
    { id: 'pgfault', title: 'PGFAULT' },
    { id: 'pgmajfault', title: 'PGMAJFAULT' },
    { id: 'pgrefill', title: 'PGREFILL' },
    { id: 'pgactivate', title: 'PGACTIVATE' },
    { id: 'pgdeactivate', title: 'PGDEACTIVATE' },
    { id: 'pglazyfree', title: 'PGLAZYFREE' },
    { id: 'pglazyfreed', title: 'PGLAZYFREED' },
    { id: 'swpin_zero', title: 'SWPIN ZERO' },
    { id: 'swpout_zero', title: 'SWPOUT ZERO' },
    { id: 'zswpin', title: 'ZSWPIN' },
    { id: 'zswpout', title: 'ZSWPOUT' },
    { id: 'zswpwb', title: 'ZSWPWB' },
    { id: 'thp_fault_alloc', title: 'THP FAULT ALLOC' },
    { id: 'thp_collapse_alloc', title: 'THP COLLAPSE ALLOC' },
    { id: 'thp_swpout', title: 'THP SWPOUT' },
    { id: 'thp_swpout_fallback', title: 'THP SWPOUT FALLBACK' },
    { id: 'numa_pages_migrated', title: 'NUMA PAGES MIGRATED' },
    { id: 'numa_pte_updates', title: 'NUMA PTE UPDATES' },
    { id: 'numa_hint_faults', title: 'NUMA HINT FAULTS' },
    { id: 'ram_usage', title: 'MEMORY CURRENT' },
    { id: 'swap_usage', title: 'SWAP CURRENT' },
    { id: 'maxram', title: 'MEMORY MAX' },
    { id: 'pressure_avg10', title: 'PRESSURE AVG10' },
    { id: 'summed_memory', title: 'SUMMED MEMORY' },
    { id: 'vm_free_used', title: 'VM FREE USED'},
    { id: 'vm_free_bufcache', title: 'VM FREE BUFCACHE'},
    { id: 'swapin', title: 'SWAP IN'},
    { id: 'swapout', title: 'SWAP OUT'},
    { id: 'pgpgin', title: 'PGPG IN'},
    { id: 'pgpgout', title: 'PGPG OUT'},
    { id: 'host_cpu', title: 'HOST CPU'},
    { id: 'load_average', title: 'LOAD AVERAGE'},
];

for(let elt of cgroup_headers) {
    console.log(`${elt.id}: INTEGER;`)
}
