#!/bin/bash


# lot_cgroup.py cgroups_stats/cgroups_stats.csv TIME SLAB_RECLAIMABLE,SLAB_UNRECLAIMABLE,SLAB RAM_USAGE,SWAP_USAGE

./scripts/plot_cgroup.py $1 TIME ANON,FILE,KERNEL_STACK,PAGETABLES,SEC_PAGETABLES RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME SLAB,SLAB_RECLAIMABLE,SLAB_UNRECLAIMABLE RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME SLAB_RECLAIMABLE RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME SHMEM,ZSWAP,ZSWAPPED RAM_USAGE,SWAP_USAGE

./scripts/plot_cgroup.py $1 TIME ANON,FILE,KERNEL_STACK,PAGETABLES,SEC_PAGETABLES,SHMEM,SLAB_RECLAIMABLE,SLAB_UNRECLAIMABLE,SOCK,ZSWAP,ZSWAPPED,PERCPU
./scripts/plot_cgroup.py $1 TIME FILE,KERNEL_STACK,PAGETABLES,SEC_PAGETABLES,SHMEM,SLAB_RECLAIMABLE,SLAB_UNRECLAIMABLE,SOCK,ZSWAP,ZSWAPPED,PERCPU
./scripts/plot_cgroup.py $1 TIME KERNEL_STACK,SHMEM,SLAB_RECLAIMABLE,SOCK,ZSWAP,ZSWAPPED,PERCPU

./scripts/plot_cgroup.py $1 TIME ACTIVE_FILE,INACTIVE_FILE RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME ACTIVE_ANON,INACTIVE_ANON,RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME MAXRAM,ACTIVE_ANON,INACTIVE_ANON,RAM_USAGE,SWAP_USAGE
./scripts/plot_cgroup.py $1 TIME ACTIVE_ANON,INACTIVE_ANON,ANON PRESSURE_AVG10
